#!/usr/bin/env python3
"""fix_keyworddata.py - offset-preserving rebuild of KeyWordData.dat.

The KEYWORD dictionary UI addresses description LINES by position (splice
compaction scrambles the boxes: mid-word line starts, leftover JP, overflow).
So this file must keep its ORIGINAL byte layout:

  * desc segments: overwrite text in place, [prefix][english][space pad][NUL@orig].
  * names <= slot: overwrite in place, NUL-padded.
  * names >  slot: append at end + repoint their SOFS entry (grow_files-style;
    appending shifts nothing).

Inputs:  work/Logic/Dat/FixedData/KeyWordData.dat      (pristine JP)
         build/keyword_entries.json                    (entry map: offsets/caps/prefixes)
         build/keyword_desc_en.json                    (merged EN descriptions, key=0x<name_off>)
Output:  build/en/Logic/Dat/FixedData/KeyWordData.dat  (overwrites the apply result)

Run AFTER `deploy.py apply Logic` (deploy.py calls this automatically).
The KeyWordData worksheet is intentionally blank (en="") - this script is the
only writer for this file.
"""
import json, os, re, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "tools"))
import fixh_grow

WRAP = 45          # box clips ~47 half-width cells (verified in-game 2026-07-07)
# Underlined <terms> render ~1.67x wider than their text (the term field uses the
# UNPATCHED full-width advance while plain text uses the K=0.6 EBOOT patch), so a
# tag costs its length x1.7 display cells.
TAG_COST = 1.7

# PLAINTEXT_TERMS (env OG2_PLAINTEXT_TERMS=1): render <term> links as PLAIN
# tight text by stripping the < > brackets before wrapping. Rationale (2026-07-08
# screenshots): inline term glyphs still draw FULL-WIDTH in the keyword/dict
# boxes, so a line containing a link overflows its fixed positional slot and the
# link + trailing text CLIP (vanish) - this is the "malformed paragraphs" and
# "wrong glossary links". Stripping brackets makes terms plain, tight, wrappable
# words: paragraphs render complete, no clipping. Cost = lose the underline/link
# affordance until the window-family term-advance EBOOT fix lands.
# DEFAULT OFF (2026-07-09 in-game finding): term links are AUTO-GENERATED by
# keyword-name matching - they appear with or without brackets. The flag only
# changes OUR wrap budgeting: brackets-on reserves the 1.7x field (complete but
# ragged lines); plaintext packs tight and the auto-drawn 1.67x field then
# overflows the box (the old "clipped paragraphs"). So brackets-on is strictly
# safer until the window-family term-field width patch lands. REVERSIBLE.
PLAINTEXT_TERMS = os.environ.get("OG2_PLAINTEXT_TERMS_LIB",
                                 os.environ.get("OG2_PLAINTEXT_TERMS", "1")) == "1"


def strip_terms(text):
    """<Name> -> Name when PLAINTEXT_TERMS; leaves NAMEFIX-abbreviated content.
    Also collapses the abbrev-period + sentence-period doubling that stripping
    exposes ('Isurugi Heavy Ind..' -> 'Ind.'), without touching '...' ellipses."""
    if not PLAINTEXT_TERMS:
        return text
    text = TAGIN.sub(r"\1", text)
    return re.sub(r"(?<!\.)\.\.(?!\.)", ".", text)
# a <link span> is atomic INCLUDING attached punctuation ("<Tesla Drive>", <DC>.);
# spans contain spaces, so they must be matched before plain \S+ splitting
SPAN = re.compile(r"\S*<[^<>]*>\S*|\S+")
TAGIN = re.compile(r"<([^<>]*)>")

# The 12 names that exceed their in-place slot: appending+SOFS-repoint broke the
# TITLE render (shows garbage), so they are ABBREVIATED to fit their slot instead.
NAMEFIX = {
    "Alpha Link Coefficient": "Alpha Link Coef.",
    "Isurugi Heavy Industries": "Isurugi Heavy Ind.",
    "Instructor Corps": "Kyoudotai",
    "Colony Integration Army": "Colony Integ. Army",
    "Shura Rebellion": "Shura Revolt",
    "Earth Federation Army": "Earth Fed Army",
    "Earth Federation Government": "Earth Fed Gov't",
    "Barrier of Harmony": "Harmony Barrier",
    "Special Combat Skills Squad": "Aggressors",
    "Special Unit": "S.Unit",
    "Antarctic Incident": "Antarctica",
    "Elemental Lord": "Masoukishin",
}


def disp_cost(tok):
    """display cells a token consumes: plain chars x1, <tag> content x1.7."""
    plain = TAGIN.sub("", tok)
    tags = sum(len(m) for m in TAGIN.findall(tok))
    return len(plain) + tags * TAG_COST


def wrap_into(text, caps, cells):
    """Greedy word-wrap into len(caps) lines. Line i must satisfy BOTH its byte
    capacity caps[i] AND the display budget cells[i] (tags weighted x1.7).
    '\n' forces a new line. Returns list of line strings or None if no fit."""
    lines = [""] * len(caps)
    cost = [0.0] * len(caps)
    li = 0
    for para in text.split("\n"):
        if li >= len(caps):
            return None
        for tok in SPAN.findall(para):
            c = disp_cost(tok)
            while True:
                cur = lines[li]
                cand = tok if not cur else cur + " " + tok
                add = c if not cur else c + 1
                if len(cand.encode("utf-8")) <= caps[li] and cost[li] + add <= cells[li]:
                    lines[li] = cand
                    cost[li] += add
                    break
                li += 1
                if li >= len(caps):
                    return None
        li += 1  # paragraph break -> next line
    return lines


def main():
    jp_path = os.path.join(REPO, "work", "Logic", "Dat", "FixedData", "KeyWordData.dat")
    out_path = os.path.join(REPO, "build", "en", "Logic", "Dat", "FixedData", "KeyWordData.dat")
    ents = json.load(open(os.path.join(REPO, "build", "keyword_entries.json"), encoding="utf-8"))
    desc_en = json.load(open(os.path.join(REPO, "build", "keyword_desc_en.json"), encoding="utf-8"))

    src = open(jp_path, "rb").read()
    d = bytearray(src)
    grow_edits = {}   # file offset -> long name (append+repoint)
    problems = []

    for e in ents:
        key = f"0x{e['name_off']:06X}"
        name = NAMEFIX.get((e.get("name_en") or "").strip(), (e.get("name_en") or "").strip())
        # --- name (must fit in place; append+repoint breaks the title render) ---
        if name:
            nb = name.encode("utf-8")
            if len(nb) > e["name_cap"]:
                problems.append((key, name, f"NAME {len(nb)}B > slot {e['name_cap']}B"))
            else:
                off = e["name_off"]
                d[off:off + e["name_cap"]] = nb + b"\x00" * (e["name_cap"] - len(nb))
        # --- description ---
        en = (desc_en.get(key) or "").strip()
        # keep inline <tags> consistent with abbreviated keyword names
        for full, abbr in NAMEFIX.items():
            en = en.replace(f"<{full}>", f"<{abbr}>")
        en = strip_terms(en)  # PLAINTEXT_TERMS: <Name> -> Name (see flag docstring)
        en = re.sub(r"\s+", " ", en).strip()  # flow continuously: no hard breaks (they cause mid-blank gaps in these small boxes)
        if not en:
            if e["segs"]:
                problems.append((key, e["name_en"], "NO TRANSLATION"))
            continue
        caps = [s["cap"] - s["prefix"] for s in e["segs"]]
        cells = [min(s["cap"] - s["prefix"], WRAP) for s in e["segs"]]
        lines = wrap_into(en, caps, cells)
        if lines is None:  # drop paragraph breaks to reclaim end-of-paragraph slack
            lines = wrap_into(en.replace("\n", " "), caps, cells)
        if lines is None:
            problems.append((key, e["name_en"], f"OVERFLOW budget={sum(caps)} len={len(en)}"))
            continue
        for s, line in zip(e["segs"], lines):
            start = s["off"] + s["prefix"]
            room = s["cap"] - s["prefix"]
            lb = line.encode("utf-8")
            assert len(lb) <= room, (key, s["off"])
            # keep prefix bytes; text + SPACE padding; original NUL terminator stays
            d[start:start + room] = lb + b" " * (room - len(lb))

    data = bytes(d)
    if grow_edits:
        data, refused = fixh_grow.grow_files(data, grow_edits)
        for off in refused:
            problems.append((hex(off), grow_edits[off], "GROW REFUSED (no SOFS ref)"))

    # gates: size (only appended growth), non-text bytes untouched
    assert len(data) >= len(src)
    if not grow_edits:
        assert len(data) == len(src)
    # every segment's terminator NUL still in place
    for e in ents:
        for s in e["segs"]:
            assert data[s["off"] + s["cap"]] == 0, hex(s["off"])

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    open(out_path, "wb").write(data)
    print(f"fix_keyworddata: {len(ents)} entries, {len(grow_edits)} names appended, "
          f"{len(problems)} problems -> {out_path}")
    for p in problems:
        print("  !!", p)
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
